services:
  postgres:
    image: postgres:18
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
    name: postgres_data_vol
